default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  username: agenda_grupo_musical
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
